apiVersion: v1
kind: Service
metadata:
  # The Ingress routes traffic to this service by name
  name: frontend-service
  labels:
    app: {{ .Release.Name }}-frontend
spec:
  type: {{ .Values.service.type }}
  selector:
    # Routes traffic to pods with this label
    app: {{ .Release.Name }}-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}